# Generated by Django 5.1 on 2024-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_feature_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.TextField(max_length=500),
        ),
    ]
