# Generated by Django 5.1 on 2024-08-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_feature_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.TextField(max_length=50000),
        ),
    ]
