# Generated by Django 5.1 on 2024-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_feature_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDescription', models.TextField(max_length=500)),
                ('Topic', models.CharField(max_length=100)),
                ('TopicOverView', models.TextField(max_length=1000)),
                ('TopicDtails', models.TextField(max_length=16000000)),
            ],
        ),
        migrations.DeleteModel(
            name='feature',
        ),
    ]
