# Generated by Django 5.1 on 2024-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_my_model_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_model',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
