# Generated by Django 5.1 on 2024-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_my_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_model',
            name='image',
            field=models.ImageField(null='images/main1.jpeg', upload_to='images/'),
        ),
    ]
