# Generated by Django 5.1 on 2024-08-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_my_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_model',
            name='image',
        ),
    ]
