# Generated by Django 5.1 on 2024-08-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_my_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('CourseID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDescription', models.TextField(max_length=1000)),
                ('CourseImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_ID', models.CharField(max_length=50)),
                ('TopicName', models.CharField(max_length=500)),
                ('Topicimage', models.ImageField(upload_to='image/')),
                ('TopicOverView', models.TextField(max_length=2000)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.DeleteModel(
            name='my_model',
        ),
    ]
