# Generated by Django 5.1 on 2024-08-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_course_topic_delete_my_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_ID',
            new_name='TopicID',
        ),
    ]
