# Generated by Django 5.1 on 2024-08-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_topic_id_alter_topic_topicid'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic1',
            fields=[
                ('TopicID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TopicName', models.CharField(max_length=500)),
                ('Topicimage', models.ImageField(upload_to='image/')),
                ('TopicOverView', models.TextField(max_length=2000)),
            ],
        ),
    ]
