# Generated by Django 5.1 on 2024-08-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_topic1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='CourseID',
        ),
        migrations.DeleteModel(
            name='topic1',
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
