# Generated by Django 5.1 on 2024-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_topic_courseid_delete_topic1_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=200)),
                ('TopicName', models.CharField(max_length=200)),
                ('TopicDetails', models.TextField(max_length=1600000)),
            ],
        ),
        migrations.DeleteModel(
            name='topic',
        ),
    ]
