# Generated by Django 5.1 on 2024-08-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_course_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseName',
        ),
    ]
