# Generated by Django 5.1 on 2024-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_course_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=2000)),
                ('topictitle', models.CharField(max_length=2000)),
                ('tittleDefinition', models.CharField(max_length=2000)),
                ('firstP', models.CharField(max_length=2000)),
                ('firstPExpl', models.CharField(max_length=2000)),
                ('secondp', models.CharField(max_length=2000)),
                ('secondPExp', models.CharField(max_length=2000)),
                ('Explaination', models.CharField(max_length=20000)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
