# Generated by Django 5.1 on 2024-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_course1_delete_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course1',
            new_name='course',
        ),
    ]
